export default {
  LOGIN_BEGIN: 'LOGIN_BEGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',

  REGISTER_BEGIN: 'REGISTER_BEGIN',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',

  ONE_WIDGET_LOAD_BEGIN: 'ONE_WIDGET_LOAD_BEGIN',
  ONE_WIDGET_LOAD_SUCCESS: 'ONE_WIDGET_LOAD_SUCCESS',
  ONE_WIDGET_LOAD_ERROR: 'ONE_WIDGET_LOAD_ERROR',

  All_WIDGETS_LOAD_BEGIN: 'All_WIDGETS_LOAD_BEGIN',
  All_WIDGETS_LOAD_SUCCESS: 'All_WIDGETS_LOAD_SUCCESS',
  All_WIDGETS_LOAD_ERROR: 'All_WIDGETS_LOAD_ERROR',

  PERSONAL_WIDGETS_LOAD_BEGIN: 'PERSONAL_WIDGETS_LOAD_BEGIN',
  PERSONAL_WIDGETS_LOAD_SUCCESS: 'PERSONAL_WIDGETS_LOAD_SUCCESS',
  PERSONAL_WIDGETS_LOAD_ERROR: 'PERSONAL_WIDGETS_LOAD_ERROR',

  PROFILE_LOAD_BEGIN: 'PROFILE_LOAD_BEGIN',
  PROFILE_LOAD_SUCCESS: 'PROFILE_LOAD_SUCCESS',
  PROFILE_LOAD_ERROR: 'PROFILE_LOAD_ERROR',

  TEAMS_LOAD_BEGIN: 'TEAMS_LOAD_BEGIN',
  TEAMS_LOAD_SUCCESS: 'TEAMS_LOAD_SUCCESS',
  TEAMS_LOAD_ERROR: 'TEAMS_LOAD_ERROR',

  ADD_WIDGET_BEGIN: 'ADD_WIDGET_BEGIN',
  ADD_WIDGET_SUCCESS: 'ADD_WIDGET_SUCCESS',
  ADD_WIDGET_ERROR: 'ADD_WIDGET_ERROR',
  REMOVE_WIDGET_BEGIN: 'REMOVE_WIDGET_BEGIN',
  REMOVE_WIDGET_SUCCESS: 'REMOVE_WIDGET_SUCCESS',
  REMOVE_WIDGET_ERROR: 'REMOVE_WIDGET_ERROR',

  LOGOUT: 'LOGOUT',
}

