export default {
  LOGIN_BEGIN: 'LOGIN_BEGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',

  LOGOUT_BEGIN: 'LOGOUT_BEGIN',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_ERROR: 'LOGOUT_ERROR',

  REGISTER_BEGIN: 'REGISTER_BEGIN',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',

  WIDGETS_LOAD_BEGIN: 'WIDGETS_LOAD_BEGIN',
  WIDGETS_LOAD_SUCCESS: 'WIDGETS_LOAD_SUCCESS',
  WIDGETS_LOAD_ERROR: 'WIDGETS_LOAD_ERROR',

  TEAMS_LOAD_BEGIN: 'TEAMS_LOAD_BEGIN',
  TEAMS_LOAD_SUCCESS: 'TEAMS_LOAD_SUCCESS',
  TEAMS_LOAD_ERROR: 'TEAMS_LOAD_ERROR',

  ADD_WIDGET_BEGIN: 'ADD_WIDGET_BEGIN',
  ADD_WIDGET_SUCCESS: 'ADD_WIDGET_SUCCESS',
  ADD_WIDGET_ERROR: 'ADD_WIDGET_ERROR',

  LOGOUT: 'LOGOUT',
}

