export default {
  LOGIN_BEGIN: 'LOGIN_BEGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  LOGOUT_BEGIN: 'LOGOUT_BEGIN',
  LOGOUT_ERROR: 'LOGOUT_ERROR',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

  REGISTER_BEGIN: 'REGISTER_BEGIN',
  REGISTER_ERROR: 'REGISTER_ERROR',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',

  LOGOUT: 'LOGOUT',
}

